# Grafana Data Source Configuration
apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  # Primary Prometheus Data Source
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    password: ""
    user: ""
    database: ""
    basicAuth: false
    basicAuthUser: ""
    basicAuthPassword: ""
    withCredentials: false
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ""
      manageAlerts: true
      alertmanagerUid: ""
    secureJsonData:
      basicAuthPassword: ""
    version: 1
    editable: true

  # Optional: Loki for Log Aggregation (if implemented)
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    password: ""
    user: ""
    database: ""
    basicAuth: false
    basicAuthUser: ""
    basicAuthPassword: ""
    withCredentials: false
    isDefault: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: 'prometheus'
          matcherRegex: 'trace_id=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'
    version: 1
    editable: true

  # Optional: Jaeger for Distributed Tracing (if implemented)
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    password: ""
    user: ""
    database: ""
    basicAuth: false
    basicAuthUser: ""
    basicAuthPassword: ""
    withCredentials: false
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [
          { key: 'service.name', value: 'service' },
          { key: 'service.namespace', value: 'namespace' }
        ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
    version: 1
    editable: true