global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # FastAPI Application Metrics
  - job_name: 'etl-platform'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/api/v1/monitoring/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # System Metrics via Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    
  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    
  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    
  # Grafana Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 60s
    
  # Health Check Endpoint (no authentication)
  - job_name: 'etl-platform-health'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/api/v1/monitoring/health'
    scrape_interval: 15s
    scrape_timeout: 5s